### ISSUE TITLE
bug: TaskEntity not updated after pause

### ISSUE THREAD

**Issue by DJafari** [yuanwenbing/DownloadManager#5]
https://github.com/yuanwenbing/DownloadManager/blob/master/library/src/main/java/com/yuan/library/dmanager/download/DownloadTask.java#L123

according to this, `mDownloadDao.update(mTaskEntity);` when task paused or canceled never called when paused or cancel a task

i think you must update functions to this : 

```java
void pause() {
        mTaskEntity.setTaskStatus(TaskStatus.TASK_STATUS_PAUSE);
        mDownloadDao.update(mTaskEntity);
        handler.sendEmptyMessage(TaskStatus.TASK_STATUS_PAUSE);
    }

    void queue() {
        mTaskEntity.setTaskStatus(TaskStatus.TASK_STATUS_QUEUE);
        mDownloadDao.update(mTaskEntity);
        handler.sendEmptyMessage(TaskStatus.TASK_STATUS_QUEUE);
    }

    void cancel() {
        mTaskEntity.setTaskStatus(TaskStatus.TASK_STATUS_CANCEL);
        mDownloadDao.update(mTaskEntity);
        handler.sendEmptyMessage(TaskStatus.TASK_STATUS_CANCEL);
    }
```

**Comment by yuanwenbing** [comment]
Thanks!
I have add the code " mDownloadDao.update(mTaskEntity)" in the pause method!
when the task status is the "queue"，don't need update the database.
when the task status is the "cancel", will delete the task from the database, add the code "mDownloadDao.delete(mTaskEntity)" int cancel method.
