### ISSUE TITLE
Cancel task error 

### ISSUE THREAD

**Issue by sonshark** [yuanwenbing/DownloadManager#7]
When download link   Error 404.0 - Not Found, cacel task error: 

org.greenrobot.greendao.DaoException: Entity has no key at org.greenrobot.greendao.AbstractDao.getKeyVerified(AbstractDao.java:928) at org.greenrobot.greendao.AbstractDao.delete(AbstractDao.java:625) at org.greenrobot.greendao.AbstractDaoSession.delete(AbstractDaoSession.java:100) at com.yuan.library.dmanager.db.DaoManager.delete(DaoManager.java:52) at com.yuan.library.dmanager.download.DownloadTask.cancel(DownloadTask.java:188) at com.yuan.library.dmanager.download.DownloadManager.cancelTask(DownloadManager.java:175)

**Comment by yuanwenbing** [comment]
Thanks, I have fixed the bug in v1.1.7.
