### ISSUE TITLE
Crash on Init 

### ISSUE THREAD

**Issue by Mahan3340** [yuanwenbing/DownloadManager#8]
Crashes at the very first moment at DownloadManager.getInstance().init(this,3)

**Comment by yuanwenbing** [comment]
sorry, can you send me the log information in the comment, I can't find the crash bug.

**Comment by Mahan3340** [comment]
Actually it works on a Test Project I Recently Created but  DownloadManager.getInstance().getTask(taskId) returns null with a simple/(http://...).gethashcode()

**Comment by yuanwenbing** [comment]
I have add the "null" validation in the demo. 
Because it is used as a framework, so some empty judgments need to be added in the demo.
